Feature/java11 neo4jv4
jQAssistant/jqa-java-plugin pull request #40
Opened 2022-12-09 15:56 UTC by DirkMahler

2022-12-09 21:16 UTC, StephanPirnbaum requested changes
Just for understanding: Why was the Java label added to multiple queries?

2022-12-09 21:16 UTC, StephanPirnbaum commented on status.txt
> +Java 11
Please remove this file

2022-12-11 16:23 UTC, DirkMahler commented on status.txt
> +Java 11
Removed

2022-12-11 16:47 UTC, StephanPirnbaum approved these changes

2022-12-12 07:40 UTC, obfischer approved these changes

2022-12-12 10:32 UTC, merged